# Generated by Django 4.1.7 on 2023-03-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='girls',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
