# Generated by Django 4.1.7 on 2023-03-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0002_girls_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girls',
            old_name='user_img',
            new_name='user_url',
        ),
    ]
