# Generated by Django 4.1.7 on 2023-03-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0003_rename_user_img_girls_user_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girls',
            old_name='user_url',
            new_name='onlyfans_url',
        ),
    ]
